/**
 * @module mcp-layer
 * @description Aggregate entrypoint for the MCP Layer workspace packages.
 * @note This file is autogenerated by src/generate.js. Manual edits will be overwritten.
 */

/**
 * Package namespace from `@mcp-layer/attach`.
 * @type {typeof import('@mcp-layer/attach')}
 */
export * as attach from '@mcp-layer/attach';

/**
 * Package namespace from `@mcp-layer/cli`.
 * @type {typeof import('@mcp-layer/cli')}
 */
export * as cli from '@mcp-layer/cli';

/**
 * Package namespace from `@mcp-layer/config`.
 * @type {typeof import('@mcp-layer/config')}
 */
export * as config from '@mcp-layer/config';

/**
 * Package namespace from `@mcp-layer/connect`.
 * @type {typeof import('@mcp-layer/connect')}
 */
export * as connect from '@mcp-layer/connect';

/**
 * Package namespace from `@mcp-layer/error`.
 * @type {typeof import('@mcp-layer/error')}
 */
export * as error from '@mcp-layer/error';

/**
 * Package namespace from `@mcp-layer/gateway`.
 * @type {typeof import('@mcp-layer/gateway')}
 */
export * as gateway from '@mcp-layer/gateway';

/**
 * Package namespace from `@mcp-layer/graphql`.
 * @type {typeof import('@mcp-layer/graphql')}
 */
export * as graphql from '@mcp-layer/graphql';

/**
 * Package namespace from `@mcp-layer/manager`.
 * @type {typeof import('@mcp-layer/manager')}
 */
export * as manager from '@mcp-layer/manager';

/**
 * Package namespace from `@mcp-layer/openapi`.
 * @type {typeof import('@mcp-layer/openapi')}
 */
export * as openapi from '@mcp-layer/openapi';

/**
 * Package namespace from `@mcp-layer/rest`.
 * @type {typeof import('@mcp-layer/rest')}
 */
export * as rest from '@mcp-layer/rest';

/**
 * Package namespace from `@mcp-layer/schema`.
 * @type {typeof import('@mcp-layer/schema')}
 */
export * as schema from '@mcp-layer/schema';

/**
 * Package namespace from `@mcp-layer/session`.
 * @type {typeof import('@mcp-layer/session')}
 */
export * as session from '@mcp-layer/session';

/**
 * Package namespace from `@mcp-layer/test-server`.
 * @type {typeof import('@mcp-layer/test-server')}
 */
export * as testServer from '@mcp-layer/test-server';

